#include "Mips.h"

unordered_map<string, Mips::Instruction> Mips::instructions = {
        {"lui",   {0x0F, 0x00, Format::I, {Parameter::RT, Parameter::IMM16}}},
        {"addi",  {0x08, 0x00, Format::I, {Parameter::RT, Parameter::RS, Parameter::IMM16}}},
        {"addiu", {0x09, 0x00, Format::I, {Parameter::RT, Parameter::RS, Parameter::IMM16}}},
        {"slti",  {0x0A, 0x00, Format::I, {Parameter::RT, Parameter::RS, Parameter::IMM16}}},
        {"sltiu", {0x0B, 0x00, Format::I, {Parameter::RT, Parameter::RS, Parameter::IMM16}}},
        {"andi",  {0x0C, 0x00, Format::I, {Parameter::RT, Parameter::RS, Parameter::IMM16}}},
        {"ori",   {0x0D, 0x00, Format::I, {Parameter::RT, Parameter::RS, Parameter::IMM16}}},
        {"xori",  {0x0E, 0x00, Format::I, {Parameter::RT, Parameter::RS, Parameter::IMM16}}},
        {"lui",   {0x0F, 0x00, Format::I, {Parameter::RT, Parameter::IMM16}}},
        {"sll",   {0x00, 0x00, Format::R, {Parameter::RD, Parameter::RT, Parameter::SHIFT}}},
        {"srl",   {0x00, 0x02, Format::R, {Parameter::RD, Parameter::RT, Parameter::SHIFT}}},
        {"sra",   {0x00, 0x03, Format::R, {Parameter::RD, Parameter::RT, Parameter::SHIFT}}},
        {"sllv",  {0x00, 0x04, Format::R, {Parameter::RD, Parameter::RT, Parameter::RS}}},
        {"srlv",  {0x00, 0x06, Format::R, {Parameter::RD, Parameter::RT, Parameter::RS}}},
        {"srav",  {0x00, 0x07, Format::R, {Parameter::RD, Parameter::RT, Parameter::RS}}},
        {"mfhi",  {0x00, 0x10, Format::R, {Parameter::RD}}},
        {"mthi",  {0x00, 0x11, Format::R, {Parameter::RS}}},
        {"mflo",  {0x00, 0x12, Format::R, {Parameter::RD}}},
        {"mtlo",  {0x00, 0x13, Format::R, {Parameter::RS}}},
        {"mult",  {0x00, 0x18, Format::R, {Parameter::RS, Parameter::RT}}},
        {"multu", {0x00, 0x19, Format::R, {Parameter::RS, Parameter::RT}}},
        {"div",   {0x00, 0x1A, Format::R, {Parameter::RS, Parameter::RT}}},
        {"divu",  {0x00, 0x1B, Format::R, {Parameter::RS, Parameter::RT}}},
        {"add",   {0x00, 0x20, Format::R, {Parameter::RD, Parameter::RS, Parameter::RT}}},
        {"addu",  {0x00, 0x21, Format::R, {Parameter::RD, Parameter::RS, Parameter::RT}}},
        {"sub",   {0x00, 0x22, Format::R, {Parameter::RD, Parameter::RS, Parameter::RT}}},
        {"subu",  {0x00, 0x23, Format::R, {Parameter::RD, Parameter::RS, Parameter::RT}}},
        {"and",   {0x00, 0x24, Format::R, {Parameter::RD, Parameter::RS, Parameter::RT}}},
        {"or",    {0x00, 0x25, Format::R, {Parameter::RD, Parameter::RS, Parameter::RT}}},
        {"xor",   {0x00, 0x26, Format::R, {Parameter::RD, Parameter::RS, Parameter::RT}}},
        {"nor",   {0x00, 0x27, Format::R, {Parameter::RD, Parameter::RS, Parameter::RT}}},
        {"slt",   {0x00, 0x2A, Format::R, {Parameter::RD, Parameter::RS, Parameter::RT}}},
        {"sltu",  {0x00, 0x2B, Format::R, {Parameter::RD, Parameter::RS, Parameter::RT}}}
};

unordered_map<string, uint8_t> Mips::registers = {
        {"$0",    0x00},
        {"$zero", 0x00},
        {"$1",    0x01},
        {"$at",   0x01},
        {"$2",    0x02},
        {"$v0",   0x02},
        {"$3",    0x03},
        {"$v1",   0x03},
        {"$4",    0x04},
        {"$a0",   0x04},
        {"$5",    0x05},
        {"$a1",   0x05},
        {"$6",    0x06},
        {"$a2",   0x06},
        {"$7",    0x07},
        {"$a3",   0x07},
        {"$8",    0x08},
        {"$t0",   0x08},
        {"$9",    0x09},
        {"$t1",   0x09},
        {"$10",   0x0A},
        {"$t2",   0x0A},
        {"$11",   0x0B},
        {"$t3",   0x0B},
        {"$12",   0x0C},
        {"$t4",   0x0C},
        {"$13",   0x0D},
        {"$t5",   0x0D},
        {"$14",   0x0E},
        {"$t6",   0x0E},
        {"$15",   0x0F},
        {"$t7",   0x0F},
        {"$16",   0x10},
        {"$s0",   0x10},
        {"$17",   0x11},
        {"$s1",   0x11},
        {"$18",   0x12},
        {"$s2",   0x12},
        {"$19",   0x13},
        {"$s3",   0x13},
        {"$20",   0x14},
        {"$s4",   0x14},
        {"$21",   0x15},
        {"$s5",   0x15},
        {"$22",   0x16},
        {"$s6",   0x16},
        {"$23",   0x17},
        {"$s7",   0x17},
        {"$24",   0x18},
        {"$t8",   0x18},
        {"$25",   0x19},
        {"$t9",   0x19},
        {"$26",   0x1A},
        {"$k0",   0x1A},
        {"$27",   0x1B},
        {"$k1",   0x1B},
        {"$28",   0x1C},
        {"$gp",   0x1C},
        {"$29",   0x1D},
        {"$sp",   0x1D},
        {"$30",   0x1E},
        {"$fp",   0x1E},
        {"$31",   0x1F},
        {"$ra",   0x1F}
};
